# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'FreeWallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeWallet
  pod 'Charts'

end
